stages:
  - lint
  - build
  - test
  - deploy

# Процент покрытия тестов
variables:
  COVERAGE_THRESHOLD: 30

.default-go-job: &default-go-job
  image: golang:1.24.1
  cache:
    key:
      files:
        - go.sum
    paths:
      - $GOPATH/pkg/mod
      - $GOPATH/bin
      - $CI_PROJECT_DIR/.cache/go-build
  before_script:
    - go env -w GOPATH=/go
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

lint_common:
  <<: *default-go-job
  stage: lint
  image: golang:1.24.1
  script:
    - cd common
    - go build ./...
    - golangci-lint run --timeout 2m ./...

lint_analytics:
  <<: *default-go-job
  stage: lint
  image: golang:1.24.1
  script:
    - cd analytics
    - go build ./...
    - golangci-lint run --timeout 2m ./...

lint_user_service:
  <<: *default-go-job
  stage: lint
  image: golang:1.24.1
  script:
    - cd user_service
    - go build ./...
    - golangci-lint run --timeout 2m ./...

lint_shortener:
  <<: *default-go-job
  stage: lint
  image: golang:1.24.1
  script:
    - cd shortener
    - go build ./...
    - golangci-lint run --timeout 2m ./...


build:
  <<: *default-go-job
  stage: build
  image: golang:1.24.1
  script:
    - echo "🔨 Building all services"
    - cd shortener && go build -v ./...
    - cd ../user_service && go build -v ./...

test-shortener:
  <<: *default-go-job
  stage: test
  image: golang:1.24.1
  script:
    - cd shortener
    - go test ./tests -coverpkg=./internal/service,./internal/service/utils,./internal/service/helper -coverprofile=cover.out
    - |
      TOTAL_COVERAGE=$(go tool cover -func=cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
      echo "📊 shortener total coverage: ${TOTAL_COVERAGE}%"
      MIN_COVERAGE=30.0
      COMP_RESULT=$(echo "$TOTAL_COVERAGE < $MIN_COVERAGE" | bc -l)
      if [[ "$COMP_RESULT" -eq 1 ]]; then
        echo "❌ Coverage too low for shortener: ${TOTAL_COVERAGE}% (required ≥ ${MIN_COVERAGE}%)"
        exit 1
      else
        echo "✅ Coverage OK: ${TOTAL_COVERAGE}%"
      fi

test-user-service:
  <<: *default-go-job
  stage: test
  image: golang:1.24.1
  script:
    - cd user_service
    - go test ./tests -coverpkg=./internal/service,./internal/utils -coverprofile=cover.out
    - |
      TOTAL_COVERAGE=$(go tool cover -func=cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
      echo "📊 user_service total coverage: ${TOTAL_COVERAGE}%"
      MIN_COVERAGE=30.0
      COMP_RESULT=$(echo "$TOTAL_COVERAGE < $MIN_COVERAGE" | bc -l)
      if [[ "$COMP_RESULT" -eq 1 ]]; then
        echo "❌ Coverage too low for user_service: ${TOTAL_COVERAGE}% (required ≥ ${MIN_COVERAGE}%)"
        exit 1
      else
        echo "✅ Coverage OK: ${TOTAL_COVERAGE}%"
      fi

test-analytics:
  <<: *default-go-job
  stage: test
  image: golang:1.24.1
  script:
    - cd user_service
    - go test ./tests -coverpkg=./internal/service,./internal/service/helper -coverprofile=cover.out
    - |
      TOTAL_COVERAGE=$(go tool cover -func=cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
      echo "📊 analytics total coverage: ${TOTAL_COVERAGE}%"
      MIN_COVERAGE=30.0
      COMP_RESULT=$(echo "$TOTAL_COVERAGE < $MIN_COVERAGE" | bc -l)
      if [[ "$COMP_RESULT" -eq 1 ]]; then
        echo "❌ Coverage too low for analytics: ${TOTAL_COVERAGE}% (required ≥ ${MIN_COVERAGE}%)"
        exit 1
      else
        echo "✅ Coverage OK: ${TOTAL_COVERAGE}%"
      fi

deploy:
  stage: deploy
  environment: production
  script:
    - echo "🚀 Deploying application..."
    - echo "✅ Application successfully deployed."
