// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: api/tokenservice.proto

package tokenservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_api_tokenservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_api_tokenservice_proto_rawDescGZIP(), []int{0}
}

func (x *TokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TokenGetUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenGetUserIDRequest) Reset() {
	*x = TokenGetUserIDRequest{}
	mi := &file_api_tokenservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenGetUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenGetUserIDRequest) ProtoMessage() {}

func (x *TokenGetUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenGetUserIDRequest.ProtoReflect.Descriptor instead.
func (*TokenGetUserIDRequest) Descriptor() ([]byte, []int) {
	return file_api_tokenservice_proto_rawDescGZIP(), []int{1}
}

func (x *TokenGetUserIDRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenGetUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenGetUserIDResponse) Reset() {
	*x = TokenGetUserIDResponse{}
	mi := &file_api_tokenservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenGetUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenGetUserIDResponse) ProtoMessage() {}

func (x *TokenGetUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenGetUserIDResponse.ProtoReflect.Descriptor instead.
func (*TokenGetUserIDResponse) Descriptor() ([]byte, []int) {
	return file_api_tokenservice_proto_rawDescGZIP(), []int{2}
}

func (x *TokenGetUserIDResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TokenCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenCheckRequest) Reset() {
	*x = TokenCheckRequest{}
	mi := &file_api_tokenservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCheckRequest) ProtoMessage() {}

func (x *TokenCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCheckRequest.ProtoReflect.Descriptor instead.
func (*TokenCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_tokenservice_proto_rawDescGZIP(), []int{3}
}

func (x *TokenCheckRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenCheckRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenCheckResponse) Reset() {
	*x = TokenCheckResponse{}
	mi := &file_api_tokenservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCheckResponse) ProtoMessage() {}

func (x *TokenCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCheckResponse.ProtoReflect.Descriptor instead.
func (*TokenCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_tokenservice_proto_rawDescGZIP(), []int{4}
}

func (x *TokenCheckResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type TokenCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenCreateResponse) Reset() {
	*x = TokenCreateResponse{}
	mi := &file_api_tokenservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCreateResponse) ProtoMessage() {}

func (x *TokenCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCreateResponse.ProtoReflect.Descriptor instead.
func (*TokenCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_tokenservice_proto_rawDescGZIP(), []int{5}
}

func (x *TokenCreateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDeleteResponse) Reset() {
	*x = TokenDeleteResponse{}
	mi := &file_api_tokenservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDeleteResponse) ProtoMessage() {}

func (x *TokenDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDeleteResponse.ProtoReflect.Descriptor instead.
func (*TokenDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_tokenservice_proto_rawDescGZIP(), []int{6}
}

func (x *TokenDeleteResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_api_tokenservice_proto protoreflect.FileDescriptor

const file_api_tokenservice_proto_rawDesc = "" +
	"\n" +
	"\x16api/tokenservice.proto\x12\x03api\"'\n" +
	"\fTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"-\n" +
	"\x15TokenGetUserIDRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"1\n" +
	"\x16TokenGetUserIDResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\x11TokenCheckRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\",\n" +
	"\x12TokenCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"+\n" +
	"\x13TokenCreateResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"-\n" +
	"\x13TokenDeleteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2\x90\x02\n" +
	"\fTokenService\x12=\n" +
	"\n" +
	"TokenCheck\x12\x16.api.TokenCheckRequest\x1a\x17.api.TokenCheckResponse\x12:\n" +
	"\vTokenCreate\x12\x11.api.TokenRequest\x1a\x18.api.TokenCreateResponse\x12:\n" +
	"\vTokenDelete\x12\x11.api.TokenRequest\x1a\x18.api.TokenDeleteResponse\x12I\n" +
	"\x0eTokenGetUserID\x12\x1a.api.TokenGetUserIDRequest\x1a\x1b.api.TokenGetUserIDResponseB\x16Z\x14pkg/api/tokenserviceb\x06proto3"

var (
	file_api_tokenservice_proto_rawDescOnce sync.Once
	file_api_tokenservice_proto_rawDescData []byte
)

func file_api_tokenservice_proto_rawDescGZIP() []byte {
	file_api_tokenservice_proto_rawDescOnce.Do(func() {
		file_api_tokenservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tokenservice_proto_rawDesc), len(file_api_tokenservice_proto_rawDesc)))
	})
	return file_api_tokenservice_proto_rawDescData
}

var file_api_tokenservice_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_tokenservice_proto_goTypes = []any{
	(*TokenRequest)(nil),           // 0: api.TokenRequest
	(*TokenGetUserIDRequest)(nil),  // 1: api.TokenGetUserIDRequest
	(*TokenGetUserIDResponse)(nil), // 2: api.TokenGetUserIDResponse
	(*TokenCheckRequest)(nil),      // 3: api.TokenCheckRequest
	(*TokenCheckResponse)(nil),     // 4: api.TokenCheckResponse
	(*TokenCreateResponse)(nil),    // 5: api.TokenCreateResponse
	(*TokenDeleteResponse)(nil),    // 6: api.TokenDeleteResponse
}
var file_api_tokenservice_proto_depIdxs = []int32{
	3, // 0: api.TokenService.TokenCheck:input_type -> api.TokenCheckRequest
	0, // 1: api.TokenService.TokenCreate:input_type -> api.TokenRequest
	0, // 2: api.TokenService.TokenDelete:input_type -> api.TokenRequest
	1, // 3: api.TokenService.TokenGetUserID:input_type -> api.TokenGetUserIDRequest
	4, // 4: api.TokenService.TokenCheck:output_type -> api.TokenCheckResponse
	5, // 5: api.TokenService.TokenCreate:output_type -> api.TokenCreateResponse
	6, // 6: api.TokenService.TokenDelete:output_type -> api.TokenDeleteResponse
	2, // 7: api.TokenService.TokenGetUserID:output_type -> api.TokenGetUserIDResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_tokenservice_proto_init() }
func file_api_tokenservice_proto_init() {
	if File_api_tokenservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tokenservice_proto_rawDesc), len(file_api_tokenservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tokenservice_proto_goTypes,
		DependencyIndexes: file_api_tokenservice_proto_depIdxs,
		MessageInfos:      file_api_tokenservice_proto_msgTypes,
	}.Build()
	File_api_tokenservice_proto = out.File
	file_api_tokenservice_proto_goTypes = nil
	file_api_tokenservice_proto_depIdxs = nil
}
