// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: api/user_service.proto

package user_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          *int64                 `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3,oneof" json:"tg_id,omitempty"`
	IsStaff       *bool                  `protobuf:"varint,2,opt,name=is_staff,json=isStaff,proto3,oneof" json:"is_staff,omitempty"`
	IsAdmin       *bool                  `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3,oneof" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetTgId() int64 {
	if x != nil && x.TgId != nil {
		return *x.TgId
	}
	return 0
}

func (x *CreateUserRequest) GetIsStaff() bool {
	if x != nil && x.IsStaff != nil {
		return *x.IsStaff
	}
	return false
}

func (x *CreateUserRequest) GetIsAdmin() bool {
	if x != nil && x.IsAdmin != nil {
		return *x.IsAdmin
	}
	return false
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_api_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// внутри проверям роль и отдаем строкой
	Role          string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	TgId          *int64 `protobuf:"varint,3,opt,name=tg_id,json=tgId,proto3,oneof" json:"tg_id,omitempty"`
	LinkCount     int32  `protobuf:"varint,4,opt,name=link_count,json=linkCount,proto3" json:"link_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_api_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetUserResponse) GetTgId() int64 {
	if x != nil && x.TgId != nil {
		return *x.TgId
	}
	return 0
}

func (x *GetUserResponse) GetLinkCount() int32 {
	if x != nil {
		return x.LinkCount
	}
	return 0
}

type GetUserIDByTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDByTokenRequest) Reset() {
	*x = GetUserIDByTokenRequest{}
	mi := &file_api_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDByTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDByTokenRequest) ProtoMessage() {}

func (x *GetUserIDByTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDByTokenRequest.ProtoReflect.Descriptor instead.
func (*GetUserIDByTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserIDByTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserIDByTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDByTokenResponse) Reset() {
	*x = GetUserIDByTokenResponse{}
	mi := &file_api_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDByTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDByTokenResponse) ProtoMessage() {}

func (x *GetUserIDByTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDByTokenResponse.ProtoReflect.Descriptor instead.
func (*GetUserIDByTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserIDByTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserIDByTokenResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GetUserIDByTgIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int64                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDByTgIDRequest) Reset() {
	*x = GetUserIDByTgIDRequest{}
	mi := &file_api_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDByTgIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDByTgIDRequest) ProtoMessage() {}

func (x *GetUserIDByTgIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDByTgIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserIDByTgIDRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserIDByTgIDRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

type GetUserIDByTgIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDByTgIDResponse) Reset() {
	*x = GetUserIDByTgIDResponse{}
	mi := &file_api_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDByTgIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDByTgIDResponse) ProtoMessage() {}

func (x *GetUserIDByTgIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDByTgIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserIDByTgIDResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserIDByTgIDResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserIDByTgIDResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type TokenCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenCheckRequest) Reset() {
	*x = TokenCheckRequest{}
	mi := &file_api_user_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCheckRequest) ProtoMessage() {}

func (x *TokenCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCheckRequest.ProtoReflect.Descriptor instead.
func (*TokenCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{8}
}

func (x *TokenCheckRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenCheckRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenCheckResponse) Reset() {
	*x = TokenCheckResponse{}
	mi := &file_api_user_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCheckResponse) ProtoMessage() {}

func (x *TokenCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCheckResponse.ProtoReflect.Descriptor instead.
func (*TokenCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{9}
}

func (x *TokenCheckResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_api_user_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_api_user_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_user_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_api_user_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpdateUserRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// не трогать если пустой
	TgId          *int64 `protobuf:"varint,2,opt,name=tg_id,json=tgId,proto3,oneof" json:"tg_id,omitempty"`
	IsStaff       *bool  `protobuf:"varint,3,opt,name=is_staff,json=isStaff,proto3,oneof" json:"is_staff,omitempty"`
	IsAdmin       *bool  `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3,oneof" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_user_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetTgId() int64 {
	if x != nil && x.TgId != nil {
		return *x.TgId
	}
	return 0
}

func (x *UpdateUserRequest) GetIsStaff() bool {
	if x != nil && x.IsStaff != nil {
		return *x.IsStaff
	}
	return false
}

func (x *UpdateUserRequest) GetIsAdmin() bool {
	if x != nil && x.IsAdmin != nil {
		return *x.IsAdmin
	}
	return false
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_api_user_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_api_user_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_api_user_service_proto protoreflect.FileDescriptor

const file_api_user_service_proto_rawDesc = "" +
	"\n" +
	"\x16api/user_service.proto\x12\x03api\"\x91\x01\n" +
	"\x11CreateUserRequest\x12\x18\n" +
	"\x05tg_id\x18\x01 \x01(\x03H\x00R\x04tgId\x88\x01\x01\x12\x1e\n" +
	"\bis_staff\x18\x02 \x01(\bH\x01R\aisStaff\x88\x01\x01\x12\x1e\n" +
	"\bis_admin\x18\x03 \x01(\bH\x02R\aisAdmin\x88\x01\x01B\b\n" +
	"\x06_tg_idB\v\n" +
	"\t_is_staffB\v\n" +
	"\t_is_admin\"C\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x81\x01\n" +
	"\x0fGetUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\x05tg_id\x18\x03 \x01(\x03H\x00R\x04tgId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"link_count\x18\x04 \x01(\x05R\tlinkCountB\b\n" +
	"\x06_tg_id\"/\n" +
	"\x17GetUserIDByTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"K\n" +
	"\x18GetUserIDByTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"-\n" +
	"\x16GetUserIDByTgIDRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x03R\x04tgId\"J\n" +
	"\x17GetUserIDByTgIDResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"B\n" +
	"\x11TokenCheckRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\",\n" +
	"\x12TokenCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"D\n" +
	"\x13RefreshTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\",\n" +
	"\x14RefreshTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x12DeleteUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\xaa\x01\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\x05tg_id\x18\x02 \x01(\x03H\x00R\x04tgId\x88\x01\x01\x12\x1e\n" +
	"\bis_staff\x18\x03 \x01(\bH\x01R\aisStaff\x88\x01\x01\x12\x1e\n" +
	"\bis_admin\x18\x04 \x01(\bH\x02R\aisAdmin\x88\x01\x01B\b\n" +
	"\x06_tg_idB\v\n" +
	"\t_is_staffB\v\n" +
	"\t_is_admin\",\n" +
	"\x12UpdateUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2\xa2\x04\n" +
	"\vUserService\x12=\n" +
	"\n" +
	"CreateUser\x12\x16.api.CreateUserRequest\x1a\x17.api.CreateUserResponse\x124\n" +
	"\aGetUser\x12\x13.api.GetUserRequest\x1a\x14.api.GetUserResponse\x12O\n" +
	"\x10GetUserIDByToken\x12\x1c.api.GetUserIDByTokenRequest\x1a\x1d.api.GetUserIDByTokenResponse\x12L\n" +
	"\x0fGetUserIDByTgID\x12\x1b.api.GetUserIDByTgIDRequest\x1a\x1c.api.GetUserIDByTgIDResponse\x12=\n" +
	"\n" +
	"UpdateUser\x12\x16.api.UpdateUserRequest\x1a\x17.api.UpdateUserResponse\x12=\n" +
	"\n" +
	"CheckToken\x12\x16.api.TokenCheckRequest\x1a\x17.api.TokenCheckResponse\x12C\n" +
	"\fRefreshToken\x12\x18.api.RefreshTokenRequest\x1a\x19.api.RefreshTokenResponse\x12<\n" +
	"\n" +
	"DeleteUser\x12\x16.api.DeleteUserRequest\x1a\x16.api.DeleteUserRequestB\x16Z\x14pkg/api/user_serviceb\x06proto3"

var (
	file_api_user_service_proto_rawDescOnce sync.Once
	file_api_user_service_proto_rawDescData []byte
)

func file_api_user_service_proto_rawDescGZIP() []byte {
	file_api_user_service_proto_rawDescOnce.Do(func() {
		file_api_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_service_proto_rawDesc), len(file_api_user_service_proto_rawDesc)))
	})
	return file_api_user_service_proto_rawDescData
}

var file_api_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_user_service_proto_goTypes = []any{
	(*CreateUserRequest)(nil),        // 0: api.CreateUserRequest
	(*CreateUserResponse)(nil),       // 1: api.CreateUserResponse
	(*GetUserRequest)(nil),           // 2: api.GetUserRequest
	(*GetUserResponse)(nil),          // 3: api.GetUserResponse
	(*GetUserIDByTokenRequest)(nil),  // 4: api.GetUserIDByTokenRequest
	(*GetUserIDByTokenResponse)(nil), // 5: api.GetUserIDByTokenResponse
	(*GetUserIDByTgIDRequest)(nil),   // 6: api.GetUserIDByTgIDRequest
	(*GetUserIDByTgIDResponse)(nil),  // 7: api.GetUserIDByTgIDResponse
	(*TokenCheckRequest)(nil),        // 8: api.TokenCheckRequest
	(*TokenCheckResponse)(nil),       // 9: api.TokenCheckResponse
	(*RefreshTokenRequest)(nil),      // 10: api.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),     // 11: api.RefreshTokenResponse
	(*DeleteUserRequest)(nil),        // 12: api.DeleteUserRequest
	(*DeleteUserResponse)(nil),       // 13: api.DeleteUserResponse
	(*UpdateUserRequest)(nil),        // 14: api.UpdateUserRequest
	(*UpdateUserResponse)(nil),       // 15: api.UpdateUserResponse
}
var file_api_user_service_proto_depIdxs = []int32{
	0,  // 0: api.UserService.CreateUser:input_type -> api.CreateUserRequest
	2,  // 1: api.UserService.GetUser:input_type -> api.GetUserRequest
	4,  // 2: api.UserService.GetUserIDByToken:input_type -> api.GetUserIDByTokenRequest
	6,  // 3: api.UserService.GetUserIDByTgID:input_type -> api.GetUserIDByTgIDRequest
	14, // 4: api.UserService.UpdateUser:input_type -> api.UpdateUserRequest
	8,  // 5: api.UserService.CheckToken:input_type -> api.TokenCheckRequest
	10, // 6: api.UserService.RefreshToken:input_type -> api.RefreshTokenRequest
	12, // 7: api.UserService.DeleteUser:input_type -> api.DeleteUserRequest
	1,  // 8: api.UserService.CreateUser:output_type -> api.CreateUserResponse
	3,  // 9: api.UserService.GetUser:output_type -> api.GetUserResponse
	5,  // 10: api.UserService.GetUserIDByToken:output_type -> api.GetUserIDByTokenResponse
	7,  // 11: api.UserService.GetUserIDByTgID:output_type -> api.GetUserIDByTgIDResponse
	15, // 12: api.UserService.UpdateUser:output_type -> api.UpdateUserResponse
	9,  // 13: api.UserService.CheckToken:output_type -> api.TokenCheckResponse
	11, // 14: api.UserService.RefreshToken:output_type -> api.RefreshTokenResponse
	12, // 15: api.UserService.DeleteUser:output_type -> api.DeleteUserRequest
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_user_service_proto_init() }
func file_api_user_service_proto_init() {
	if File_api_user_service_proto != nil {
		return
	}
	file_api_user_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_user_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_user_service_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_service_proto_rawDesc), len(file_api_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_service_proto_goTypes,
		DependencyIndexes: file_api_user_service_proto_depIdxs,
		MessageInfos:      file_api_user_service_proto_msgTypes,
	}.Build()
	File_api_user_service_proto = out.File
	file_api_user_service_proto_goTypes = nil
	file_api_user_service_proto_depIdxs = nil
}
