// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: api/shortener.proto

package shortener

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       *string                `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Generated     bool                   `protobuf:"varint,3,opt,name=generated,proto3" json:"generated,omitempty"`
	ShortLink     string                 `protobuf:"bytes,4,opt,name=short_link,json=shortLink,proto3" json:"short_link,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	ExpireAt      *string                `protobuf:"bytes,6,opt,name=expire_at,json=expireAt,proto3,oneof" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_api_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateLinkRequest) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *CreateLinkRequest) GetGenerated() bool {
	if x != nil {
		return x.Generated
	}
	return false
}

func (x *CreateLinkRequest) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

func (x *CreateLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateLinkRequest) GetExpireAt() string {
	if x != nil && x.ExpireAt != nil {
		return *x.ExpireAt
	}
	return ""
}

type UpdateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       *string                `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Generated     bool                   `protobuf:"varint,4,opt,name=generated,proto3" json:"generated,omitempty"`
	ShortLink     string                 `protobuf:"bytes,5,opt,name=short_link,json=shortLink,proto3" json:"short_link,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	ExpireAt      *string                `protobuf:"bytes,7,opt,name=expire_at,json=expireAt,proto3,oneof" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLinkRequest) Reset() {
	*x = UpdateLinkRequest{}
	mi := &file_api_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkRequest) ProtoMessage() {}

func (x *UpdateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateLinkRequest) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *UpdateLinkRequest) GetGenerated() bool {
	if x != nil {
		return x.Generated
	}
	return false
}

func (x *UpdateLinkRequest) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

func (x *UpdateLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateLinkRequest) GetExpireAt() string {
	if x != nil && x.ExpireAt != nil {
		return *x.ExpireAt
	}
	return ""
}

type DeleteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_api_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       *string                `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Generated     bool                   `protobuf:"varint,4,opt,name=generated,proto3" json:"generated,omitempty"`
	ShortLink     string                 `protobuf:"bytes,5,opt,name=short_link,json=shortLink,proto3" json:"short_link,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpireAt      string                 `protobuf:"bytes,8,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_api_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *Link) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Link) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Link) GetGroupId() string {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return ""
}

func (x *Link) GetGenerated() bool {
	if x != nil {
		return x.Generated
	}
	return false
}

func (x *Link) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Link) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Link) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

type Url struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Url) Reset() {
	*x = Url{}
	mi := &file_api_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *Url) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeleteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkResponse) Reset() {
	*x = DeleteLinkResponse{}
	mi := &file_api_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkResponse) ProtoMessage() {}

func (x *DeleteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteLinkResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GetLinksCountByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinksCountByUserIdRequest) Reset() {
	*x = GetLinksCountByUserIdRequest{}
	mi := &file_api_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinksCountByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinksCountByUserIdRequest) ProtoMessage() {}

func (x *GetLinksCountByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinksCountByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetLinksCountByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *GetLinksCountByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetLinksCountByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinksCountByUserIdResponse) Reset() {
	*x = GetLinksCountByUserIdResponse{}
	mi := &file_api_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinksCountByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinksCountByUserIdResponse) ProtoMessage() {}

func (x *GetLinksCountByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinksCountByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetLinksCountByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *GetLinksCountByUserIdResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_shortener_proto protoreflect.FileDescriptor

const file_api_shortener_proto_rawDesc = "" +
	"\n" +
	"\x13api/shortener.proto\x12\x03api\"\xd8\x01\n" +
	"\x11CreateLinkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\bgroup_id\x18\x02 \x01(\tH\x00R\agroupId\x88\x01\x01\x12\x1c\n" +
	"\tgenerated\x18\x03 \x01(\bR\tgenerated\x12\x1d\n" +
	"\n" +
	"short_link\x18\x04 \x01(\tR\tshortLink\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12 \n" +
	"\texpire_at\x18\x06 \x01(\tH\x01R\bexpireAt\x88\x01\x01B\v\n" +
	"\t_group_idB\f\n" +
	"\n" +
	"_expire_at\"\xe8\x01\n" +
	"\x11UpdateLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\bgroup_id\x18\x03 \x01(\tH\x00R\agroupId\x88\x01\x01\x12\x1c\n" +
	"\tgenerated\x18\x04 \x01(\bR\tgenerated\x12\x1d\n" +
	"\n" +
	"short_link\x18\x05 \x01(\tR\tshortLink\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12 \n" +
	"\texpire_at\x18\a \x01(\tH\x01R\bexpireAt\x88\x01\x01B\v\n" +
	"\t_group_idB\f\n" +
	"\n" +
	"_expire_at\"#\n" +
	"\x11DeleteLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe7\x01\n" +
	"\x04Link\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\bgroup_id\x18\x03 \x01(\tH\x00R\agroupId\x88\x01\x01\x12\x1c\n" +
	"\tgenerated\x18\x04 \x01(\bR\tgenerated\x12\x1d\n" +
	"\n" +
	"short_link\x18\x05 \x01(\tR\tshortLink\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\texpire_at\x18\b \x01(\tR\bexpireAtB\v\n" +
	"\t_group_id\"\x17\n" +
	"\x03Url\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\",\n" +
	"\x12DeleteLinkResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"7\n" +
	"\x1cGetLinksCountByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"5\n" +
	"\x1dGetLinksCountByUserIdResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2\xb6\x02\n" +
	"\x10ShortenerService\x12\x1e\n" +
	"\bRedirect\x12\b.api.Url\x1a\b.api.Url\x122\n" +
	"\rCreateNewLink\x12\x16.api.CreateLinkRequest\x1a\t.api.Link\x12/\n" +
	"\n" +
	"UpdateLink\x12\x16.api.UpdateLinkRequest\x1a\t.api.Link\x12=\n" +
	"\n" +
	"DeleteLink\x12\x16.api.DeleteLinkRequest\x1a\x17.api.DeleteLinkResponse\x12^\n" +
	"\x15GetLinksCountByUserId\x12!.api.GetLinksCountByUserIdRequest\x1a\".api.GetLinksCountByUserIdResponseB\x13Z\x11pkg/api/shortenerb\x06proto3"

var (
	file_api_shortener_proto_rawDescOnce sync.Once
	file_api_shortener_proto_rawDescData []byte
)

func file_api_shortener_proto_rawDescGZIP() []byte {
	file_api_shortener_proto_rawDescOnce.Do(func() {
		file_api_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_shortener_proto_rawDesc), len(file_api_shortener_proto_rawDesc)))
	})
	return file_api_shortener_proto_rawDescData
}

var file_api_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_shortener_proto_goTypes = []any{
	(*CreateLinkRequest)(nil),             // 0: api.CreateLinkRequest
	(*UpdateLinkRequest)(nil),             // 1: api.UpdateLinkRequest
	(*DeleteLinkRequest)(nil),             // 2: api.DeleteLinkRequest
	(*Link)(nil),                          // 3: api.Link
	(*Url)(nil),                           // 4: api.Url
	(*DeleteLinkResponse)(nil),            // 5: api.DeleteLinkResponse
	(*GetLinksCountByUserIdRequest)(nil),  // 6: api.GetLinksCountByUserIdRequest
	(*GetLinksCountByUserIdResponse)(nil), // 7: api.GetLinksCountByUserIdResponse
}
var file_api_shortener_proto_depIdxs = []int32{
	4, // 0: api.ShortenerService.Redirect:input_type -> api.Url
	0, // 1: api.ShortenerService.CreateNewLink:input_type -> api.CreateLinkRequest
	1, // 2: api.ShortenerService.UpdateLink:input_type -> api.UpdateLinkRequest
	2, // 3: api.ShortenerService.DeleteLink:input_type -> api.DeleteLinkRequest
	6, // 4: api.ShortenerService.GetLinksCountByUserId:input_type -> api.GetLinksCountByUserIdRequest
	4, // 5: api.ShortenerService.Redirect:output_type -> api.Url
	3, // 6: api.ShortenerService.CreateNewLink:output_type -> api.Link
	3, // 7: api.ShortenerService.UpdateLink:output_type -> api.Link
	5, // 8: api.ShortenerService.DeleteLink:output_type -> api.DeleteLinkResponse
	7, // 9: api.ShortenerService.GetLinksCountByUserId:output_type -> api.GetLinksCountByUserIdResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_shortener_proto_init() }
func file_api_shortener_proto_init() {
	if File_api_shortener_proto != nil {
		return
	}
	file_api_shortener_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_shortener_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_shortener_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_shortener_proto_rawDesc), len(file_api_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shortener_proto_goTypes,
		DependencyIndexes: file_api_shortener_proto_depIdxs,
		MessageInfos:      file_api_shortener_proto_msgTypes,
	}.Build()
	File_api_shortener_proto = out.File
	file_api_shortener_proto_goTypes = nil
	file_api_shortener_proto_depIdxs = nil
}
